### ISSUE TITLE
Node software installation failure

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/cyclecloud-hpcpack#3]
Cloud.AwaitInstallation | Node software installation failure, retrying | 2m 37s...

[azureuser@cyclevm hpcpack]$ cyclecloud show_cluster
ADDC : started
Keypair:
Cluster nodes:
    ad:    Awaiting system boot-up 49a94be7d954bf14c405f2eed97d0e23  (10.0.0.5)
    proxy: Started 7f18189fd9ad68bd2d40fc485aa78dbd 104.40.204.110 (10.0.0.4)
Total nodes: 2

**Comment by kostas-rs** [comment]
Hi @lmiroslaw, i know its been a while but did you find out why the installation was failing? Thank you!

**Comment by carogonzalezzapata** [comment]
This issue will be fixed in the next release 8.2 with HPC Pack integration.
